#!/bin/bash
# This script dumps architecture optimization flags generated by GCC's `-march=native` option.
# Requires GCC to be installed as a depedency.
echo 'int main(){return 0;}' > test.c
gcc -v -Q -march=native -O2 test.c -o test &> test.config
rm test.c test
ARCH_OPTS=$(awk '{ printf "%s", $0 }' < test.config | awk -Ftest.c '{ print $2 }')
rm test.config
echo CFLAGS=\""$ARCH_OPTS"\"
